
create table invoice (
    id integer not null generated by default as identity,
    billing_header_id integer,
    primary key (id)
);

create table billing_header (
    id integer not null generated by default as identity,
    company_id integer,
    total_invoice_amount integer,
    total_invoice_lines integer,
    billing_id varchar(255),
    currency_code varchar(255),
    primary key (id)
);

create table billing_line_information (
    id integer not null generated by default as identity,
    invoice_id integer,
    action_type varchar(255),
    line_type varchar(255),
    product_type varchar(255),
    resource_code varchar(255),
    primary key (id)
);